### ISSUE TITLE
@github make @abeljoseph GDP

### ISSUE THREAD

**Issue by hamzanadeveloper** [abeljoseph/syde372_lab2#1]

**Comment by abeljoseph** [comment]
This will be covered in the Beta release 1.0. Resolving.

**Comment by hamzanadeveloper** [comment]
Re-opened in the Alpha-Beta 1.2.2.1 Re-release Relaunch LIVE F.A.A.N.G Update.

Duplicate of #6969

`<div>Hello World!</div>`

**Comment by abeljoseph** [comment]
Closing as I have recently obtained GDP.
